image: docker:latest

stages:
  - build

# Hidden key that defines an anchor named 'build'
.job_template: &build
  services:
    - docker:dind
  before_script:
    - echo "Building version=$BONDY_IMAGE_VERSION, variant=$BONDY_IMAGE_VARIANT"
    # - cd "$BONDY_IMAGE_VERSION"
    - image="bondy:${BONDY_IMAGE_VERSION}${BONDY_IMAGE_VARIANT:+-$BONDY_IMAGE_VARIANT}"
    # - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
    - rm -rf tmp
    - mkdir tmp
    - cp "${BONDY_IMAGE_VERSION}/${VARIANT:-.}/Dockerfile" tmp/Dockerfile
    - cp start.sh tmp/start.sh
  script:
    # Build using $VARIANT/Dockerfile orelse ./Dockerfile
    # - docker build --pull -t "$image" "${VARIANT:-.}"
    - docker build --pull -t "$image" tmp

  only:
    - master

develop:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "develop"
  <<: *build

develop-slim:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "develop"
    BONDY_IMAGE_VARIANT: "slim"
  <<: *build

# master:
#   stage: build
#   variables:
#     DIR: "master"
#   <<: *build

# master-slim:
#   stage: build
#   variables:
#     DIR: "master"
#     VARIANT: "slim"
#   <<: *build

# "0.8.5":
#   stage: build
#   variables:
#     DIR: "master"
#   <<: *build

# "0.8.5-slim":
#   stage: build
#   variables:
#     DIR: "master"
#     VARIANT: "slim"
#   <<: *build
