image: docker:master

stages:
  - build

# Hidden key that defines an anchor named 'build'
.job_template: &build
  services:
    - docker:dind
  before_script:
    - cd "$DIR"
    - eval $(awk '/VERSION=/ { sub(/@/, "-", $2); print $2; exit }' ${VARIANT:-.}/Dockerfile)
    - image="bondy:${VERSION}${VARIANT:+-$VARIANT}"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
  script:
    - docker build --pull -t "$image" "${VARIANT:-.}"
  only:
    - master


  # env:
  # - DIR=master
  # - DIR=master VARIANT=slim
  # - DIR=develop
  # - DIR=develop VARIANT=slim
  # - DIR=0.8.6
  # - DIR=0.8.6 VARIANT=slim

develop:
  stage: build
  variables:
    DIR: "develop"
  <<: *build

develop-slim:
  stage: build
  variables:
    DIR: "develop"
    VARIANT: "slim"
  <<: *build

master:
  stage: build
  variables:
    DIR: "master"
  <<: *build

master-slim:
  stage: build
  variables:
    DIR: "master"
    VARIANT: "slim"
  <<: *build

"0.8.5":
  stage: build
  variables:
    DIR: "master"
  <<: *build

"0.8.5-slim":
  stage: build
  variables:
    DIR: "master"
    VARIANT: "slim"
  <<: *build

0.8.7:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8.7"
  <<: *build

0.8.7-slim:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8.7"
    BONDY_IMAGE_VARIANT: "slim"
  <<: *build
