image: docker:latest

stages:
  - build

# Hidden key that defines an anchor named 'build'
.job_template: &build
  services:
    - docker:dind
  before_script:
    - echo "Logging in to registry $CI_REGISTRY"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Building version=$BONDY_IMAGE_VERSION, variant=$BONDY_IMAGE_VARIANT"
    # - cd "$BONDY_IMAGE_VERSION"
    - image="leapsight/bondy:${BONDY_IMAGE_VERSION}${BONDY_IMAGE_VARIANT:+-$BONDY_IMAGE_VARIANT}"
    # - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
    - rm -rf tmp
    - mkdir tmp
    - cp "${BONDY_IMAGE_VERSION}/${VARIANT:-.}/Dockerfile" tmp/Dockerfile
    - cp start.sh tmp/start.sh
  script:
    # Build using $VARIANT/Dockerfile orelse ./Dockerfile
    # - docker build --pull -t "$image" "${VARIANT:-.}"
    - docker build --pull -t "$image" tmp
    - docker push "$image"

  only:
    - master

develop:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "develop"
  <<: *build

develop-slim:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "develop"
    BONDY_IMAGE_VARIANT: "slim"
  <<: *build

master:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "master"
  <<: *build

master-slim:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "master"
    BONDY_IMAGE_VARIANT: "slim"
  <<: *build

0.8.5:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8.5"
  <<: *build

0.8.5-slim:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8.5"
    BONDY_IMAGE_VARIANT: "slim"
  <<: *build

0.8.6:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8.6"
  <<: *build

0.8.6-slim:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8.6"
    BONDY_IMAGE_VARIANT: "slim"
  <<: *build

0.8.7:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8.7"
  <<: *build

0.8.7-slim:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8.7"
    BONDY_IMAGE_VARIANT: "slim"
  <<: *build

0.8.8:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8.8"
  <<: *build

0.8.8-slim:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8.8"
    BONDY_IMAGE_VARIANT: "slim"
    BONDY_TAG: "0.8.8.2"
  <<: *build
  <<: *build