image: docker:latest

services:
  - docker:dind

env:
  - DIR=master
  - DIR=master VARIANT=slim
  - DIR=develop
  - DIR=develop VARIANT=slim
  - DIR=0.8.6
  - DIR=0.8.6 VARIANT=slim

build:
  stage: build
  before_script:
    - cd "$DIR"
    - eval $(awk '/VERSION=/ { sub(/@/, "-", $2); print $2; exit }' ${VARIANT:-.}/Dockerfile)
    - image="bondy:${VERSION}${VARIANT:+-$VARIANT}"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
  script:
    - docker build --pull -t "$image" "${VARIANT:-.}"
  after_script:
    - docker images
  # only:
  #   - tags
  #   - master
  #   - develop
