image: docker:latest

stages:
  - build

# Hidden key that defines an anchor named 'build'
.job_template: &build
  services:
    - docker:dind
  before_script:
    - echo "CI_JOB_NAME = $CI_JOB_NAME"
    - BONDY_TAG="${BONDY_TAG:-BONDY_IMAGE_VERSION}"
    - echo "Logging in to registry $CI_REGISTRY"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Building tag=$BONDY_TAG name=$CI_JOB_NAME version=$BONDY_IMAGE_VERSION, variant=$BONDY_IMAGE_VARIANT"
    # - image="leapsight/bondy:${BONDY_IMAGE_VERSION}${BONDY_IMAGE_VARIANT:+-$BONDY_IMAGE_VARIANT}"
    - image="leapsight/bondy:${CI_JOB_NAME}"
    # - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
    - rm -rf tmp
    - mkdir tmp
    - cp "${BONDY_IMAGE_VERSION}/${VARIANT:-.}/Dockerfile" tmp/Dockerfile
    - cp start.sh tmp/start.sh
  script:
    # Build using $VARIANT/Dockerfile orelse ./Dockerfile
    # - docker build --pull -t "$image" "${VARIANT:-.}"
    - docker build --build-arg BONDY_TAG=${BONDY_TAG} --pull -t "$image" tmp
    - docker push "$image"

  only:
    - master



# ==============================================================================
# DEVELOP
# ==============================================================================



develop:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "1.0.0-beta"
    BONDY_TAG: "develop"
  <<: *build

develop-slim:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "1.0.0-beta"
    BONDY_TAG: "develop"
    BONDY_IMAGE_VARIANT: "slim"
  <<: *build



# ==============================================================================
# MASTER
# ==============================================================================



master:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8"
    BONDY_TAG: "master"
  <<: *build

master-slim:
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "0.8"
    BONDY_TAG: "master"
    BONDY_IMAGE_VARIANT: "slim"
  <<: *build



# ==============================================================================
# 0.8
# ==============================================================================

# 0.8.7:
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.7"
#   <<: *build

# 0.8.7-slim:
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.7"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# 0.8.8:
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.8.3"
#   <<: *build

# 0.8.8-slim:
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.8.3"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# 0.8.8.3:
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.8.3"
#   <<: *build

# 0.8.8.3-slim:
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.8.3"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# 0.8.8.4:
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.8.4"
#   <<: *build

# 0.8.8.4-slim:
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.8.4"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# 0.8.8.2:
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.8.2"
#   <<: *build

# 0.8.8.2-slim:
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.8.2"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '0.8':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.8.3"
#   <<: *build

# '0.8-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.8"
#     BONDY_TAG: "0.8.8.3"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# ==============================================================================
# 0.9
# ==============================================================================


# '0.9-SNAPSHOT':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "0.9.0-SNAPSHOT"
#   <<: *build

# '0.9-SNAPSHOT-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "0.9.0-SNAPSHOT"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '0.9-SNAPSHOT-SSO':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "0.9.0-SNAPSHOT-SSO"
#   <<: *build

# '0.9-SNAPSHOT-SSO-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "0.9.0-SNAPSHOT-SSO"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '1.0.0-beta.1':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.1"
#   <<: *build

# '1.0.0-beta.1-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.1"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '1.0.0-beta.3':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.3"
#   <<: *build

# '1.0.0-beta.3-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.3"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '1.0.0-beta.4':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.4"
#   <<: *build

# '1.0.0-beta.4-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.4"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '1.0.0-beta.6':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.6"
#   <<: *build

# '1.0.0-beta.6-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.6"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '1.0.0-beta.7':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.7"
#   <<: *build

# '1.0.0-beta.7-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.7"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '1.0.0-beta.8':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.8"
#   <<: *build

# '1.0.0-beta.8-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.8"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '1.0.0-beta.9':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.9"
#   <<: *build

# '1.0.0-beta.9-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "0.9-SNAPSHOT"
#     BONDY_TAG: "1.0.0-beta.9"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '1.0.0-beta.10':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "1.0.0-beta"
#     BONDY_TAG: "1.0.0-beta.10"
#   <<: *build

# '1.0.0-beta.10-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "1.0.0-beta"
#     BONDY_TAG: "1.0.0-beta.10"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build


# '1.0.0-beta.11':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "1.0.0-beta"
#     BONDY_TAG: "1.0.0-beta.11"
#   <<: *build

# '1.0.0-beta.11-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "1.0.0-beta"
#     BONDY_TAG: "1.0.0-beta.11"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build


# '1.0.0-beta.12':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "1.0.0-beta"
#     BONDY_TAG: "1.0.0-beta.12"
#   <<: *build

# '1.0.0-beta.12-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "1.0.0-beta"
#     BONDY_TAG: "1.0.0-beta.12"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '1.0.0-beta.13':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "1.0.0-beta"
#     BONDY_TAG: "1.0.0-beta.13"
#   <<: *build

# '1.0.0-beta.13-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "1.0.0-beta"
#     BONDY_TAG: "1.0.0-beta.13"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

# '1.0.0-beta.14':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "1.0.0-beta"
#     BONDY_TAG: "1.0.0-beta.14"
#   <<: *build

# '1.0.0-beta.14-slim':
#   stage: build
#   variables:
#     BONDY_IMAGE_VERSION: "1.0.0-beta"
#     BONDY_TAG: "1.0.0-beta.14"
#     BONDY_IMAGE_VARIANT: "slim"
#   <<: *build

'1.0.0-beta.15':
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "1.0.0-beta"
    BONDY_TAG: "1.0.0-beta.15"
  <<: *build

'1.0.0-beta.15-slim':
  stage: build
  variables:
    BONDY_IMAGE_VERSION: "1.0.0-beta"
    BONDY_TAG: "1.0.0-beta.15"
    BONDY_IMAGE_VARIANT: "slim"
  <<: *build