FROM leapsight/bondy:develop AS builder

COPY --chown=bondy:bondy etc/security_config.json.template /bondy/etc/security_config.json.template
COPY --chown=bondy:bondy etc/bondy.conf.template /bondy/etc/bondy.conf.template
